mainpage/urls.py
from django.conf.urls import url

from mainpage import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^filtr$', views.filtr, name='filtr'),
    url(r'^edit/(?P<program_id>[0-9]+)/$', views.showedit, name='editshow'),
    url(r'^showfav/(?P<user_id>[0-9]+)/', views.showfav, name='showfav'),
    url(r'^edit/(?P<program_id>[0-9]+)/edit$', views.edit, name='edit'),
    url(r'^detail/(?P<program_id>[0-9]+)/', views.detail, name='detail'),
    url(r'^delete/(?P<program_id>[0-9]+)/', views.delete, name='delete'),
    url(r'^addfav/(?P<program_id>[0-9]+)/(?P<user_id>[0-9]+)/', views.addfav, name='addfav'),
    url(r'^deletefav/(?P<program_id>[0-9]+)/(?P<user_id>[0-9]+)/', views.deletefav, name='deletefav'),
    url(r'^login$', views.login, name='login'),
    url(r'^report$', views.report, name='report'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^registr$', views.registr, name='registr'),
    url(r'^add$', views.add, name='add')
]
app_name = 'mains'

workstudysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path

from . import settings

urlpatterns = [
    url(r'^mainpage/', include('mainpage.urls', namespace="mains")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainpage/models.py
from django.core.validators import validate_email
from django.db import models


class ProgramWork(models.Model):
    program_name = models.CharField(max_length=100, blank=False, unique=False)
    program_picture = models.ImageField(upload_to="downloadimagesprogram/", blank=False, unique=False)
    program_describe = models.CharField(max_length=500, blank=False, unique=False)
    program_during = models.CharField(max_length=50, blank=False, unique=False)
    program_employment = models.CharField(max_length=50, blank=False, unique=False)
    program_direction = models.CharField(max_length=500, blank=False, unique=False)
    program_requirement = models.CharField(max_length=500, blank=False, unique=False)
    program_contact = models.CharField(max_length=100, blank=False, unique=False)
    program_timing = models.CharField(max_length=50, blank=False, unique=False)
    program_paying = models.CharField(max_length=50, blank=False, unique=False)
    program_count_favourite = models.IntegerField(unique=False, default=0)

    objects: models.Manager()

    def __str__(self):
        return self.program_name


class Users(models.Model):
    user_name = models.CharField(max_length=50, blank=False, unique=False)
    user_address = models.CharField(max_length=50, blank=False, validators=[validate_email], unique=True)
    user_username = models.CharField(max_length=30, blank=False, unique=True)
    user_password = models.BinaryField(max_length=60, blank=False)
    user_status = models.BooleanField(default='False')

    objects: models.Manager()

    def __str__(self):
        return self.user_username


class Favorites(models.Model):
    id = models.AutoField(primary_key=True)
    program_id = models.IntegerField(unique=False)
    user_id = models.IntegerField(unique=False)

    objects: models.Manager()

    def __str__(self):
        return self

mainpage/views.py
import random
import re
from datetime import datetime

import bcrypt
from django.db import DataError
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from docxtpl import DocxTemplate

from .models import ProgramWork, Users, Favorites


def index(request):
    latest_program_list = ProgramWork.objects.all()
    if 'user_session' in request.session:
        favours_program_list = list(
            Favorites.objects.all().filter(user_id=request.session['user_id']).values_list('program_id', flat=True))
        return render(request, 'mainpage/index.html',
                      {'username': request.session['username'], 'status': request.session['status'],
                       'user_id': request.session['user_id'], 'latest_program_list': latest_program_list,
                       'favours_program_list': favours_program_list})
    else:
        return render(request, 'mainpage/index.html', {'latest_program_list': latest_program_list})


def filtr(request):
    latest_program_list = ProgramWork.objects.all()
    if request.method == "POST":
        if len(request.POST['direction']) > 50:
            direction = ''
        else:
            direction = request.POST.get('direction')

        # employment
        employmentfull = request.POST.get('employmentfull')
        employmentpart = request.POST.get('employmentpart')
        if employmentfull == 'on':
            employmentfull = 'полн'
        else:
            employmentfull = ' '
        if employmentpart == 'on':
            employmentpart = 'част'
        else:
            employmentpart = ' '
        queryemployment = (Q(program_employment__icontains=employmentfull) &
                           Q(program_employment__icontains=employmentpart))
        if (employmentfull == 'полн') & (employmentpart == 'част'):
            queryemployment = (Q(program_employment__icontains=employmentfull) |
                               Q(program_employment__icontains=employmentpart))
        # during
        duringsixmonth = request.POST.get('duringsixmonth')
        duringsixmonthyear = request.POST.get('duringsixmonthyear')
        duringonethreeyear = request.POST.get('duringonethreeyear')
        queryduring = ''
        if duringsixmonth == 'on':
            queryduring = (Q(program_during__icontains='месяц') &
                           Q(program_during__icontains='1') |
                           Q(program_during__icontains='2') |
                           Q(program_during__icontains='3') |
                           Q(program_during__icontains='4') |
                           Q(program_during__icontains='5'))
        if duringsixmonthyear == 'on':
            queryduring = (Q(program_during__icontains='месяц') &
                           Q(program_during__icontains='6') |
                           Q(program_during__icontains='7') |
                           Q(program_during__icontains='8') |
                           Q(program_during__icontains='9') |
                           Q(program_during__icontains='10') |
                           Q(program_during__icontains='11') |
                           Q(program_during__icontains='12'))
        if duringonethreeyear == 'on':
            queryduring = (Q(program_during__icontains='год') | Q(program_during__icontains='12'))
        if (duringsixmonth != 'on') & (duringsixmonthyear != 'on') & (duringonethreeyear != 'on'):
            queryduring = Q()

        # paying
        payingpay = request.POST.get('payingpay')
        payingunpay = request.POST.get('payingunpay')
        if payingunpay == 'on':
            querypaying = (Q(program_paying__icontains='не'))
        else:
            if payingpay == 'on':
                querypaying = (~Q(program_paying__icontains='не'))
            else:
                querypaying = Q()
        if (payingunpay == 'on') & (payingpay == 'on'):
            querypaying = Q()
        latest_program_list = ProgramWork.objects.filter(Q(program_direction__icontains=direction) &
                                                         queryemployment & queryduring & querypaying)
    if 'user_session' in request.session:
        favours_program_list = list(
            Favorites.objects.all().filter(user_id=request.session['user_id']).values_list('program_id', flat=True))
        return render(request, 'mainpage/index.html',
                      {'username': request.session['username'], 'status': request.session['status'],
                       'user_id': request.session['user_id'], 'latest_program_list': latest_program_list,
                       'favours_program_list': favours_program_list})
    else:
        return render(request, 'mainpage/index.html', {'latest_program_list': latest_program_list})


def detail(request, program_id):
    program = get_object_or_404(ProgramWork, pk=program_id)
    direction_list = program.program_direction.split(';')
    requirement_list = program.program_requirement.split(';')
    if 'user_session' in request.session:
        return render(request, "mainpage/detail.html", {'program': program, 'username': request.session['username'],
                                                        'status': request.session['status'],
                                                        'direction_list': direction_list,
                                                        'requirement_list': requirement_list})
    else:
        return render(request, "mainpage/detail.html", {'program': program, 'direction_list': direction_list,
                                                        'requirement_list': requirement_list})


@csrf_exempt
def login(request):
    messagepassword = ''
    if request.method == 'POST':
        # check length
        if len(request.POST['username']) < 5 or len(request.POST['username']) > 30:
            messageusername = 'Логин должен быть не менее 5 символов'
            if len(request.POST['password']) < 6 or len(request.POST['password']) > 60:
                messagepassword = 'Пароль должен быть не менее 6 символов'
            return render(request, 'mainpage/login.html', {'messageusername': messageusername, 'username': request.POST['username'],
                                                           'messagepassword': messagepassword, 'password': request.POST['password']})
        users = Users.objects.all().filter(user_username=request.POST['username'])
        if users.count() == 0:
            message = 'Ошибка входа'
            return render(request, 'mainpage/login.html', {'message': message})
        else:
            for user in users:
                password = request.POST['password'].encode('utf-8')
                # check hash
                if bcrypt.checkpw(password, bytes(user.user_password)):
                    request.session['user_session'] = random.random()
                    request.session['username'] = request.POST['username']
                    request.session['user_id'] = user.id
                    if user.user_status:
                        request.session['status'] = 'true'
                    else:
                        request.session['status'] = 'false'
                    favours_program_list = list(
                        Favorites.objects.all().filter(user_id=request.session['user_id']).values_list('program_id', flat=True))
                    latest_program_list = ProgramWork.objects.all()
                    return render(request, 'mainpage/index.html',
                                            {'username': request.session['username'], 'status': request.session['status'],
                                             'user_id': request.session['user_id'], 'latest_program_list': latest_program_list,
                                             'favours_program_list': favours_program_list})
                else:
                    message = 'Ошибка входа'
                    return render(request, 'mainpage/login.html', {'message': message})
    else:
        return render(request, 'mainpage/login.html')


@csrf_exempt
def logout(request):
    try:
        del request.session['user_session']
        del request.session['username']
        del request.session['status']
        del request.session['user_id']
    except KeyError:
        pass
    latest_program_list = ProgramWork.objects.all()
    return render(request, 'mainpage/index.html', {'latest_program_list': latest_program_list})


@csrf_exempt
def registr(request):
    messageusername = ''
    messagepassword = ''
    messageaddress = ''
    messagefio = ''
    if request.method == 'POST':
        if len(request.POST['username']) < 5 or len(request.POST['username']) > 30:
            messageusername = "Логин должен быть не менее 5 символов"
            if len(request.POST['password']) < 6 or len(request.POST['password']) > 60:
                messagepassword = "Пароль должен быть не менее 6 символов"
                if len(request.POST['address']) < 4 or len(request.POST['address']) > 50:
                    messageaddress = "Ошибка ввода адреса электронной почты"
                    if len(request.POST['fio']) > 50:
                        messagefio = "Ошибка ввода ФИО"
            return render(request, 'mainpage/registr.html',
                          {'messageusername': messageusername, 'username': request.POST['username'],
                           'messagepassword': messagepassword, 'password': request.POST['password'],
                           'messageaddress': messageaddress, 'address': request.POST['address'],
                           'messagefio': messagefio, 'fio': request.POST['fio']})
        if re.search(r"[\w._%+-]+@[\w.-]+\.[a-zA-Z]{2,4}", request.POST['address']):
            if re.search(r"^[А-ЯЁа-яё\s]+$", request.POST['fio']):
                usernames = Users.objects.all().filter(user_username=request.POST['username'])

mainpage/templates/mainpage/addprogram.html
{% load static %}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Work&Study</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css"/>
</head>
<body>
<div class="header">
    <div class="headletter">Work & Study</div>
    Подбор стажировки для вашей будущей карьеры
    <div class="menu">
        <a href=" " class="left"></a>
    </div>
</div>
<div class="formprogram">
        <form method="post" action="add" enctype="multipart/form-data">
            <p>Название программы: <br>
            {% if messagename %}
                <input type="text" name="name" style="color: red;" required value="{{ messagename }}"/>
            {% else %}
                <input type="text" name="name" required value="{{ program_name }}"/>
            {% endif %}
            </p>
            <p>Изображение для программы: <br>
            {% if messagepicture %}
                <input type="file" name="picture" accept="image/*" style="color: red;" title="{{ messagepicture }}" required />
            {% else %}
                <input type="file" name="picture" accept="image/*"  style="color: black;" required />
            {% endif %}
            </p>
            <p>Описание программы: <br>
            {% if messagedescribe %}
                 <textarea name="describe" style="resize: none; color: red;" required >{{ messagedescribe }}</textarea>
            {% else %}
                <textarea name="describe" style="resize: none;" required >{{ program_describe }}</textarea>
            {% endif %}
            </p>
            <p>Продолжительность программы: <br>
            {% if messageduring %}
                <input type="text" style="color:red;" name="during" required value="{{ messageduring }}"/>
            {% else %}
                <input type="text" name="during" required value="{{ program_during }}"/>
            {% endif%}
            </p>
            <p>Тип занятости: <br>
            {% if messageemployment %}
                <input type="text" name="employment" style="color: red;" required value="{{ messageemployment }}"/>
            {% else %}
                <input type="text" name="employment" required value="{{ program_employment }}"/>
            {% endif %}
            </p>
            <p>Направления программы: <br>
            {% if messagedirection %}
                <textarea name="direction" style="resize: none; color: red;" required>{{ messagedirection }}</textarea>
            {% else %}
                <textarea name="direction" style="resize: none;" required>{{ program_direction }}</textarea>
            {% endif %}
            </p>
            <p>Требования к кандидатам: <br>
            {% if messagerequirement %}
                <textarea name="requirement" style="resize: none; color: red;" required>{{ messagerequirement }}</textarea>
            {% else %}
                <textarea name="requirement" style="resize: none;" required>{{ program_requirement }}</textarea>
            {% endif %}
            </p>
            <p>Контакты: <br>
            {% if messagecontact %}
                <input type="text" name="contact" style="color: red;" required value="{{ messagecontact }}"/>
            {% else %}
                <input type="text" name="contact" required value="{{ program_contact }}"/>
            {% endif %}
            </p>
            <p>Срок приема заявок: <br>
            {% if messagetiming %}
                <input type="text" name="timing" style="color: red;" required value="{{ messagetiming }}"/>
            {% else %}
                <input type="text" name="timing" required value="{{ program_timing }}"/>
            {% endif %}
            </p>
            <p>Оплата: <br>
            {% if messagepaying %}
                <input type="text" name="paying" style="color: red;" required value="{{ messagepaying }}"/>
            {% else %}
                <input type="text" name="paying" required value="{{ program_paying }}"/>
            {% endif %}
            </p>
        <p align="center"><input class="button" type="submit" value="Добавить программу"></p>
    </form>
</div>
</body>
</html>

mainpage/templates/mainpage/detail.html
{% load static %}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Work&Study</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css"/>
</head>

<body>
<div class="header">
    <div class="headletter">Work & Study</div>
    Подбор стажировки для вашей будущей карьеры
    <div class="menu">
         {% if 'user_session' in request.session%}
            <a class="right" href="{%url 'mains:login' %}">{{username}} - Выйти</a>
        {% else %}
            <a class="right" href="{%url 'mains:login' %}">Вход</a>
        {% endif %}
    </div>
</div>
<div class="programcontent">
    <br>
    <img src="/media/{{program.program_picture}}" width="65%"/>
    <p style="font-size: 20px; font-weight: bold;
              color: white; background-color: orange;">{{program.program_name}}</p>
    <p>{{program.program_describe}}</p>
    <p style="color: orange;">Продолжительность стажировки: </p><p> {{program.program_during}}</p>
    <p style="color: orange;">Тип занятости: </p><p> {{program.program_employment}}</p>
    <p style="color: orange;">Направления: </p>
        {% if direction_list %}
            <p>
               {% for direction in direction_list %}
                    {{direction}} <br>
               {% endfor %}
            </p>
        {% endif%}
    </p>
    <p style="color: orange;">Требования к кандидатам: </p>
        {% if requirement_list %}
            <p>
               {% for requirement in requirement_list %}
                     {{requirement}} </br>
               {% endfor %}
            </p>
             {% endif%}
    </p>
    <p style="color: orange;">Оплата: </p> <p>{{program.program_paying}}</p>
    <p style="color: orange;">Свяжитесь с нами: </p> <p>{{program.program_contact}}</p>
    <p style="font-size:14px;">Прием заявок: <b> {{program.program_timing}}</b></p>
</div>

</body>
</html>

mainpage/templates/mainpage/index.html
{% load static %}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Work&Study</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css"/>
</head>
<body>
<div class="header">
    <div class="headletter">Work & Study</div>
    Подбор стажировки для вашей будущей карьеры
    <div class="menu">
        {% if 'user_session' in request.session %}
            <a class="right" href="{%url 'mains:logout' %}">{{username}} - Выйти</a>
        {% else %}
            <a class="right" href="{%url 'mains:login' %}">Вход</a>
        {% endif %}
    </div>
</div>
<div class="main">
    {% if status == 'false' and 'user_session' in request.session %}
        <p><a class="button" style="margin: 2%;" href="{% url 'mains:showfav' user_id %}">Показать избранные программы</a></p>
    {% endif %}
    {% if status == 'true' and 'user_session' in request.session %}
    <p><a class="button" style="margin: 2%;" href="{% url 'mains:add' %}">Добавить новую программу стажировки</a></p>
    <p><a class="button" style="margin: 2%;" href="{% url 'mains:report' %}">Создать отчет</a></p>
    {% endif%}
    <form class="filtr" method="post" action="filtr">
        <p style="font-weight: bold;">Направление:</p>
                    {% csrf_token %}
                    <input type="text" name="direction" placeholder="Введите направление"><br>
          <p style="font-weight: bold;">Занятость:</p>
                    <input type="checkbox" name="employmentfull">Полная<br>
                    <input type="checkbox" name="employmentpart">Частичная
          <p style="font-weight: bold;">Продолжительность:</p>
                              <input type="checkbox" name="duringsixmonth">до 6 месяцев<br>
                              <input type="checkbox" name="duringsixmonthyear">от 6 месяцев до года<br>
                              <input type="checkbox" name="duringonethreeyear">от года до 3 лет
          <p style="font-weight: bold;">Оплата:</p>
                     <input type="checkbox" name="payingpay">Оплачиваемая<br>
                      <input type="checkbox" name="payingunpay">Неоплачиваемая
          <p align="center"><input class="button" type="submit" value="Подобрать"></p>
    </form>
        {% if latest_program_list %}
            {% for program in latest_program_list %}
                <div class="content">
                    <br>
                    <img src="/media/{{program.program_picture}}" width="100%" />
                    <p style="font-size: 17px; font-weight: bold;">{{program.program_name}}</p>
                    <p>{{program.program_describe}}</p>
                    <p style="font-size:14px;">Прием заявок: <b> {{program.program_timing}}</b></p>
                    <a class="button" href=" {% url 'mains:detail' program.id  %}">Подробнее</a>
                    {% if status == 'true' and 'user_session' in request.session %}
                        <a class="button" href="{% url 'mains:editshow' program.id %}">Редактировать</a>
                        <a class="button" href="{% url 'mains:delete' program.id %}">Удалить</a>
                    {% endif %}
                    {% if status == 'false' and 'user_session' in request.session%}
                        {% if favours_program_list %}
                                {% if program.id in favours_program_list %}
                                    <a class="button" href="{% url 'mains:deletefav' program.id user_id %}">Удалить из избранного</a>
                                {% else %}
                                    <a class="button" href="{% url 'mains:addfav' program.id user_id %}">Добавить в избранное</a>
                                {% endif %}
                        {% else %}
                            <a class="button" href="{% url 'mains:addfav' program.id user_id %}">Добавить в избранное</a>
                        {% endif %}
                    {% endif %}
                </div>
            {% endfor %}
        {% else %}
            <p style="font-family: 'Gerbera'; text-align: center; font-size: 18px;">Программ стажировок не найдено</p>
        {% endif %}
</div>
</body>
</html>

mainpage/templates/mainpage/login.html
{% load static %}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Work&Study</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css"/>
</head>
<body>
<div class="header">
    <div class="headletter">Work & Study</div>
    Подбор стажировки для вашей будущей карьеры
    <div class="menu">
        <a href=" " class="left"></a>
    </div>
</div>
<div class="logincontent">
        <form class="login" method="post" action="login">
            <p style="color: red;">{{ message }}</p>
            <p> Введите имя пользователя<br>
            {% if messageusername %}
                 <input type="text" name="username" style="color: red;" placeholder="Введите логин" required value="{{messageusername}}" />
            {% else %}
                <input type="text" name="username" style="color: black;" placeholder="Введите логин" required value="{{username}}" />
            {% endif %}
            </p>
            <p>Введите пароль <br>
            {% if messagepassword %}
                <input type="text" name="password" style="color: red;" placeholder="Введите пароль" required value="{{messagepassword}}"/>
            {% else %}
                <input type="password" name="password" style="color: black;" placeholder="Введите пароль" required value="{{password}}" />
            {% endif %}
            </p>
        <p align="center"><input class="button" type="submit" value="Войти"></p>
            или <br>
            <p><a href="{%url 'mains:registr'%}" style="text-decoration: none; color: black;
                                font-size: 16px; color: orange;">Зарегистрироваться</a></p>
    </form>
</div>
</body>
</html>

mainpage/templates/mainpage/registr.html
{% load static %}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Work&Study</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css"/>
</head>
<body>
<div class="header">
    <div class="headletter">Work & Study</div>
    Подбор стажировки для вашей будущей карьеры
    <div class="menu">
        <a href=" " class="left"></a>
    </div>
</div>
<div class="logincontent">
        <form class="login" method="post" action="registr">
            {% csrf_token %}
            <p style="font-size: 20px;">Добро пожаловать на сайт Work&Study</p>
            <p style="color: red;">{{ message }}</p>
            <p> Введите ваши ФИО <br>
            {% if messagefio %}
                <input type="text" name="fio" style="color: red;" placeholder="Введите ФИО" required value="{{messagefio}}"/>
            {% else %}
                <input type="text" name="fio" style="color: black;" placeholder="Введите ФИО" required value="{{fio}}"/>
            {% endif %}
            </p>
            <p> Введите адрес электронной почты <br>
            {% if messageaddress %}
                <input type="text" name="address" style="color: red;" placeholder="Введите электронную почту" required value="{{messageaddress}}" />
            {% else %}
                <input type="text" name="address" style="color: black;" placeholder="Введите электронную почту" required value="{{address}}" />
            {% endif %}
            </p>
            <p> Придумайте имя пользователя<br>
            {% if messageusername %}
                <input type="text" name="username" style="color: red;" placeholder="Введите логин" required value="{{messageusername}}"/>
            {% else %}
                 <input type="text" name="username" style="color: black;" placeholder="Введите логин" required value="{{username}}"/>
            {% endif %}
            </p>
            <p>Придумайте пароль <br>
            {% if messagepassword %}
                <input type="text" name="password" style="color: red;" placeholder="Введите пароль" required value="{{messagepassword}}"/>
            {% else %}
                <input type="password" name="password" style="color: black;" placeholder="Введите пароль" required value="{{password}}" />
            {% endif %}
            </p>
        <p align="center"><input class="button" type="submit" value="Зарегистрироваться"></p>
    </form>
</div>
</body>
</html>

mainpage/templates/mainpage/report.html
{% load static %}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Work&Study</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css"/>
</head>

<body>
<div class="header">
    <div class="headletter">Work & Study</div>
    Подбор стажировки для вашей будущей карьеры
    <div class="menu">
         {% if 'user_session' in request.session%}
            <a class="right" href="{%url 'mains:login' %}">{{username}} - Выйти</a>
        {% else %}
            <a class="right" href="{%url 'mains:login' %}">Вход</a>
        {% endif %}
    </div>
</div>
<div class="programcontent">
    <form class="report" method="post" action="report">
        <b>{{messagesuccess}}</b>
        <p> Для формирования отчета о популярных программах стажировок<br>
            необходимо ввести ФИО составителя:</p>
        {% if messagefio %}
            <input type="text" name="fio" style="color: red;" placeholder="Введите ФИО составителя" required value="{{messagefio}}"/>
        {% else %}
            <input type="text" name="fio" style="color: black;" placeholder="Введите ФИО составителя" required value="{{fio}}"/>
        {% endif %}
        <p align="center"><input class="button" type="submit" value="Получить отчет"></p>
    </form>
</div>

</body>
</html>

mainpage/templates/mainpage/showfav.html
{% load static %}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Work&Study</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css"/>
</head>
<body>
<div class="header">
    <div class="headletter">Work & Study</div>
    Подбор стажировки для вашей будущей карьеры
    <div class="menu">
        {% if 'user_session' in request.session %}
            <a class="right" href="{%url 'mains:logout' %}">{{username}} - Выйти</a>
        {% else %}
            <a class="right" href="{%url 'mains:login' %}">Вход</a>
        {% endif %}
    </div>
</div>
<div class="main">
        {% if latest_program_list %}
            {% for program in latest_program_list %}
                <div class="formprogram">
                    <br>
                    <img src="/media/{{program.program_picture}}" width="100%" />
                    <p style="font-size: 17px; font-weight: bold;">{{program.program_name}}</p>
                    <p>{{program.program_describe}}</p>
                    <p style="font-size:14px;">Прием заявок: <b> {{program.program_timing}}</b></p>
                    <a class="button" href=" {% url 'mains:detail' program.id  %}">Подробнее</a>
                    <a class="button" href="{% url 'mains:deletefav' program.id user_id %}">Удалить из избранного</a>
                </div>
            {% endfor %}
        {% else %}
            <p style="font-family: 'Gerbera'; text-align: center; font-size: 18px;">Программ стажировок не найдено</p>
        {% endif %}
</div>
</body>
</html>